### ISSUE TITLE
Anaconda-mode ValueError

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [hlissner/doom-emacs#3237]
I`m using 
python 3.6
jedi 0.17
anaconda 0.1.13
Emacs version Doom Emacs

```
anaconda_mode port 40787
<string>:99: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:99: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:155: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
<string>:131: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
<string>:99: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:99: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
<string>:155: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
<string>:131: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
127.0.0.1 - - [19/May/2020 10:31:13] ================================================================================
Traceback (most recent call last):
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 99, in wrapper
  File "<string>", line 126, in company_complete
  File "<string>", line 128, in <listcomp>
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 675, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 262, in docstring
    doc = self._get_docstring()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 684, in _get_docstring
    return super(Completion, self)._get_docstring()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/api/classes.py", line 273, in _get_docstring
    return self._name.py__doc__()
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.17.0-py3.8.egg/jedi/inference/compiled/value.py", line 329, in py__doc__
    value, = self.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/vh/.emacs.d/.local/etc/anaconda/0.1.13/service_factory-0.1.6-py3.8.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\')"}}')
```

**Comment by hlissner** [comment]
Looks like an anaconda issue. I'll close this thread since I don't think I can do anything about it from Doom's end and you've [reported it upstream](https://github.com/pythonic-emacs/anaconda-mode/issues/388).

Alternatively, you could switch to LSP by enabling the `:lang (python +lsp)` and `:tools lsp` modules and installing ms-python-lsp with `M-x lsp-install-server`.
