### ISSUE TITLE
python org-babel with :session header 

### ISSUE THREAD

**Issue by wangkev** [hlissner/doom-emacs#3242]
**What did you expect to happen?**
Have `org-babel` with `python` and `:session` header work and output result. Seems like the default `org-babel` `python` script that's run with the `:session` header doesn't always get interpreted properly.

**What actually happened?**
Had an indentation error (see below), and nothing was output.

**Additional details:**
Confirmed `org-babel` works as expected in vanilla Emacs and with `doom`, but without the `org` module. Also this seems to only be an issue when I include `:session` header. Sometimes if I execute the `org-babel` block again, it will work (i.e. `org-babel` outputs, and no indentation/parsing issue in `*Python*` buffer).

Best resources I could find so far:
- https://code.orgmode.org/jackkamm/org-mode/commit/c2fff65f36141b78d91af9d6264d0f936ee5a3a1
- https://emacs.stackexchange.com/questions/41336/src-python-in-org-mode-indentationerror-unexpected-indent

`init.el`:
```elisp
(doom! :input
       ;;chinese
       ;;japanese

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ivy               ; a search engine for love and life

       :ui
       deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       fill-column       ; a `fill-column' indicator
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;pretty-code       ; ligatures or substitute text with pretty symbols
       ;;tabs              ; an tab bar for Emacs
       ;;treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ibuffer           ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       ;;vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax            ; tasing you for every semicolon you forget
       spell             ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       ;;lsp
       ;;macos             ; MacOS-specific commands
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :lang
       ;;agda              ; types of types of types of types...
       ;;cc                ; C/C++/Obj-C madness
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp           ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;(go +lsp)         ; the hipster dialect
       ;;(haskell +dante)  ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ;
       ;;json              ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean
       ;;factor
       ;;ledger            ; an accounting system in Emacs
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org              ; organize your plain life in plain text
        +roam)
       ;;perl              ; write code no one else can comprehend
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       (python            ; beautiful is better than ugly
        +lsp)
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;rust              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;scheme            ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       ;;yaml              ; JSON, but readable

       :email
       ;;(mu4e +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens))
```

`config.el` (although have tried with the below excluded too):
```elisp
(setq python-shell-interpreter "python3")
```

`*Python*` buffer:
```python
import ast
Python 3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
try:
>>> >>> ...   File "<stdin>", line 2
    import codecs, os;__pyfile = codecs.open('''/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/pybvFjOf''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/pybvFjOf''');exec(compile(__code, '''/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/pybvFjOf''', 'exec'));
         ^
IndentationError: expected an indented block
>>>     with open('/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/babel-8x5dXm/python-RVrgqc') as f:
  File "<stdin>", line 1
    with open('/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/babel-8x5dXm/python-RVrgqc') as f:
    ^
IndentationError: unexpected indent
        __org_babel_python_ast = ast.parse(f.read())
>>>     __org_babel_python_final = __org_babel_python_ast.body[-1]
  File "<stdin>", line 1
    __org_babel_python_ast = ast.parse(f.read())
    ^
IndentationError: unexpected indent
    if isinstance(__org_babel_python_final, ast.Expr):
>>>         __org_babel_python_ast.body = __org_babel_python_ast.body[:-1]
  File "<stdin>", line 1
    __org_babel_python_final = __org_babel_python_ast.body[-1]
    ^
IndentationError: unexpected indent
        exec(compile(__org_babel_python_ast, '<string>', 'exec'))
>>>         __org_babel_python_final = eval(compile(ast.Expression(
  File "<stdin>", line 1
    if isinstance(__org_babel_python_final, ast.Expr):
    ^
IndentationError: unexpected indent
            __org_babel_python_final.value), '<string>', 'eval'))
>>>     else:
  File "<stdin>", line 1
    __org_babel_python_ast.body = __org_babel_python_ast.body[:-1]
    ^
IndentationError: unexpected indent
        exec(compile(__org_babel_python_ast, '<string>', 'exec'))
>>>         __org_babel_python_final = None
  File "<stdin>", line 1
    exec(compile(__org_babel_python_ast, '<string>', 'exec'))
    ^
IndentationError: unexpected indent
except Exception:
>>>     from traceback import format_exc
  File "<stdin>", line 1
    __org_babel_python_final = eval(compile(ast.Expression(
    ^
IndentationError: unexpected indent
    __org_babel_python_final = format_exc()
>>>     raise
  File "<stdin>", line 1
    __org_babel_python_final.value), '<string>', 'eval'))
    ^
IndentationError: unexpected indent

>>> open('/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/babel-8x5dXm/python-JoOoC9', 'w').write(str(__org_babel_python_final))
  File "<stdin>", line 1
    else:
    ^
IndentationError: unexpected indent

>>> 
  File "<stdin>", line 1
    exec(compile(__org_babel_python_ast, '<string>', 'exec'))
    ^
IndentationError: unexpected indent
'org_babel_python_eoe'
>>>   File "<stdin>", line 1
    __org_babel_python_final = None
    ^
IndentationError: unexpected indent
>>>   File "<stdin>", line 1
    except Exception:
         ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
    from traceback import format_exc
    ^
IndentationError: unexpected indent
>>>   File "<stdin>", line 1
    __org_babel_python_final = format_exc()
    ^
IndentationError: unexpected indent
>>>   File "<stdin>", line 1
    raise
    ^
IndentationError: unexpected indent
>>> >>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '__org_babel_python_final' is not defined
>>> >>> >>> 'org_babel_python_eoe'
>>> 
```

Then after a few tries, the python code will be interpreted fine:
```python
>>> import ast
>>> try:
...     with open('/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/babel-s9dZu3/python-XufMTg') as f:
...         __org_babel_python_ast = ast.parse(f.read())
...     __org_babel_python_final = __org_babel_python_ast.body[-1]
...     if isinstance(__org_babel_python_final, ast.Expr):
...         __org_babel_python_ast.body = __org_babel_python_ast.body[:-1]
...         exec(compile(__org_babel_python_ast, '<string>', 'exec'))
...         __org_babel_python_final = eval(compile(ast.Expression(
...             __org_babel_python_final.value), '<string>', 'eval'))
...     else:
...         exec(compile(__org_babel_python_ast, '<string>', 'exec'))
...         __org_babel_python_final = None
... except Exception:
...     from traceback import format_exc
...     __org_babel_python_final = format_exc()
...     raise
... 
open('/var/folders/13/x5h4fyvj3c715d6pnbd68ypm0000gn/T/babel-s9dZu3/python-Hy9Zle', 'w').write(str(__org_babel_python_final))
```

**Steps to reproduce:**
1. Install vanilla emacs
2. Confirm `org-babel` works in vanilla emacs. Minimal repro:
2a. In scratch buffer, change to `org-mode` (`M-x org-mode`)
2b. Paste below two source blocks:
```
#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)))
#+end_src

#+begin_src python :session :results raw
5
#+end_src
```
2c. Execute blocks and confirm output:
```
#+results:
5
```
2. Install doom
3. Enable org in doom config
4. Follow 2a to 2c to see no results and aforementioned traceback in `*Python*` buffer.

**System information:**
<details><pre>
```
emacs   version    27.0.91
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER GMP
        build      May 20, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/HEAD-b71b8b1 --with-gnutls --with-modules)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 94fc6f7 2020-05-20 01:10:15 -0400
        dir        ~/.dotfiles/emacs/.config/doom/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
        path       (~/.virtualenvs/py3/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin ~/.config/emacs/bin)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard fill-column hl-todo minimap modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :checkers syntax spell :tools (eval +overlay) lookup magit :lang emacs-lisp markdown (org +roam) (python +lsp) sh :config literate (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by flowersw** [comment]
I think add this to my config this may have solved it for me ```(setq org-babel-python-command "python3")``` seen in https://tecosaur.github.io/emacs-config/config.html#babel,code--1

**Comment by gpetrini** [comment]
I have the same error. I've tried @flowersw proposal and still got the same result. Is this something related to `org_babel_python_eoe`? Here is my doom configuration [link](https://github.com/gpetrini/.doom.d)

**Comment by hlissner** [comment]
@wangkev Is this still an issue? I cannot reproduce it. Please make sure you are on the latest version of Doom and on Emacs 27.1+, not 27.0.50 or earlier.

To change the interpreter python blocks in org-mode use change `org-babel-python-command` instead. Doom [sets it to `python-shell-interpreter`](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L263), but it's possible you're setting it in such a way that it gets set too early; check its value with `M-x helpful-variable RET org-babel-python-command`).

**Comment by wangkev** [comment]
I haven't tried to use the session tag since raising the issue, but re-tested just now and do not have the same error anymore (granted on a different machine). Using emacs 27.1 and doom 2.0.9.

Happy to close this issue, or can leave it open for others who appear to have the same issue?

**Comment by hlissner** [comment]
It must've been fixed at some point then. Thanks for letting me know!
