### ISSUE TITLE
"No Project" error after saving typescript file

### ISSUE THREAD

**Issue by emacsified** [hlissner/doom-emacs#3528]
**What did you expect to happen?**
Opening a typescript file starts  tide-server and the file works correctly with hinting etc.  Upon editing and saving the file, all hinting and checking stops, and a 'No Project' error from tide-server appears in the \*Messages* buffer.

`SPC m R` (tide-restart-server) fixes the issue but as soon as I edit/save the file again, this error reoccurs

**What actually happened?**

**Additional details:**
- Include a link to your private config: http://gitlab.ashmcbride.top/ashisacat/tidydots/-/tree/shared/emacs/.doom.d

Contents of the \*Messages* buffer below.
```Deprecated date/weektree capture templates changed to ‘file+olp+datetree’.
Reformatted with prettier
Wrote /Users/ash/Work/Repositories/universal_mail/producer/index.ts
"index.ts" 29L, 792C written
Error from syntax checker typescript-tide: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:141496:23)
    at ScriptInfo.getDefaultProject (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:142266:46)
    at ProjectService.doEnsureDefaultProjectForFile (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:144895:48)
    at ProjectService.ensureDefaultProjectForFile (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:144890:75)
    at IOSession.Session.getFileAndProjectWorker (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:148786:87)
    at IOSession.Session.getFileAndProject (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:148769:29)
    at IOSession.Session.getDiagnosticsWorker (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:148450:31)
    at IOSession.Session.getSyntacticDiagnosticsSync (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:148583:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:147929:61)
    at /Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/Users/ash/Work/Repositories/universal_mail/producer/node_modules/typescript/lib/tsserver.js:150866:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
    at Socket.ondata (readline.js:139:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
```

**Steps to reproduce:**
1. Open Emacs
2. Open any *.ts file
3. Edit any line
4. Save the file
5. Error Occurs.

**System information:**
<details><pre>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 46d6d0b58 2020-06-29 15:12:30 -0400
        dir        ~/.tidyDots/emacs/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/zsh
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/texinfo/bin/ ~/.nodenv/shims/ ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/TeX/texbin/ /usr/local/go/bin/ /usr/local/MacGPG2/bin/ /usr/local/share/dotnet/ ~/.dotnet/tools/ /Library/Apple/usr/bin/ /Library/Frameworks/Mono.framework/Versions/Current/Commands/ /usr/local/opt/texinfo/bin/ ~/.nodenv/shims/ ~/.cargo/bin/ ~/go/bin/ ~/go/bin/ /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +defaults) pretty-code vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools ansible docker (eval +overlay) lookup macos magit pass rgb :lang data emacs-lisp (go +lsp) json javascript latex markdown org rust sh web yaml :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (exec-path-from-shell) (wakatime-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by emacsified** [comment]
I've moved over to LSP and this issue (obviously) no longer occurs :)
