### ISSUE TITLE
Not detecting local python environment

### ISSUE THREAD

**Issue by e-eight** [hlissner/doom-emacs#4655]
**What did you expect to happen?**
...
I manage my python environments with `direnv`. In one of the projects, I have `python 3.7.0` installed. When I open any `.py` file I expect it to detect the local python installation. 

**What actually happened?**
...
However whenever I open up any `.py` file it shows `python 3.9.1` (which is my system python) on the modeline, and then complains that the required `pylint` is not installed. Even though `pylint` is installed in the local environment. I can see in the error message that it is looking for the system `pylint`.

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

```Traceback (most recent call last):
  File "/usr/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint==2.6.0', 'console_scripts', 'pylint')())
  File "/usr/lib/python3.9/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/usr/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/usr/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/usr/lib/python3.9/site-packages/pylint/checkers/base.py", line 1976, in visit_assignname
    if isinstance(utils.safe_infer(assign_type.value), astroid.ClassDef):
  File "/usr/lib/python3.9/site-packages/pylint/checkers/utils.py", line 1142, in safe_infer
    infer_gen = node.infer(context=context)
  File "/usr/lib/python3.9/site-packages/astroid/node_classes.py", line 357, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/usr/lib/python3.9/site-packages/astroid/__init__.py", line 95, in _inference_tip_cached
    result = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/astroid/brain/brain_typing.py", line 60, in infer_typing_typevar_or_newtype
    node = extract_node(TYPING_TYPE_TEMPLATE.format(typename))
  File "/usr/lib/python3.9/site-packages/astroid/builder.py", line 422, in extract_node
    tree = parse(code, module_name=module_name)
  File "/usr/lib/python3.9/site-packages/astroid/builder.py", line 279, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "/usr/lib/python3.9/site-packages/astroid/builder.py", line 142, in string_build
    module = self._data_build(data, modname, path)
  File "/usr/lib/python3.9/site-packages/astroid/builder.py", line 170, in _data_build
    raise exceptions.AstroidSyntaxError(
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 10)

Try installing a more recent version of python-pylint, and please open a bug report if the issue persists in the latest release.  Thanks!```

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>


**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.


**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
SYSTEM  type       gnu/linux
        config     x86_64-unknown-linux-gnu
        shell      /bin/bash
        uname      Linux 5.10.15_1 #1 SMP 1612978917 x86_64
        path       (~/.nvm/versions/node/v14.8.0/bin/ ~/.nix-profile/bin/ /usr/local/bin/ /usr/bin/ /bin/ ~/.local/bin/ ~/.local/texlive/2020/bin/x86_64-linux/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Nov 29, 2020
        buildopts  --with-x-toolkit=gtk2 --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --with-file-notification=inotify --with-modules --with-jpeg --with-tiff --with-gif --with-png --with-xpm --with-rsvg --without-imagemagick --with-xml2 --with-gnutls --with-sound --with-m17n-flt --with-json --without-harfbuzz --without-cairo --with-libgmp --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu 'CFLAGS=-fno-PIE -mtune=generic -O2 -pipe   -g' 'CPPFLAGS=   ' 'LDFLAGS=-no-pie -Wl,--as-needed    '
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -ADBO-Source Code Pro-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD e08c5f5 2021-02-07 23:57:44 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools direnv ein (eval +overlay) lookup magit pass pdf :lang cc data emacs-lisp (haskell +dante) (latex +latexmk) markdown (org +hugo +jupyter) python sh web :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by e-eight** [comment]
Figured out the issue. I thought Doom was using `direnv.el` instead of `envrc.el`. Now it is working as expected. Might be better to rename the module `envrc` than `direnv`.
